# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unsplash-WithRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for AutoLayout
  pod 'SnapKit'
  pod 'Then'
  
  # Pods for Image Caching
  pod 'Kingfisher'
end
